apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-demo-backend
  namespace: pipeline-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-demo-workflow
  namespace: pipeline-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-demo-backend
  namespace: pipeline-demo
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["create", "get", "list", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-demo-backend
  namespace: pipeline-demo
subjects:
  - kind: ServiceAccount
    name: pipeline-demo-backend
    namespace: pipeline-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-demo-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-demo-workflow
  namespace: pipeline-demo
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-demo-workflow
  namespace: pipeline-demo
subjects:
  - kind: ServiceAccount
    name: pipeline-demo-workflow
    namespace: pipeline-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-demo-workflow
